### ISSUE TITLE
Improve Image Quality for "Resizable Custom Crop"

### ISSUE THREAD

**Issue by gekitz** [gekitz/GKImagePicker#12]
As the image quality of the custom crop was improved with the latest commit https://github.com/gekitz/GKImagePicker/commit/2a91f31a90ad2dca02b58395a2604095f8c96fbf we should definitely improve the quality of the "Resizeable Custom Crop" too.

@Pathonhauser, any ideas on that?

**Comment by phausero** [comment]
Yap. Work in progress...
—

**Comment by jamgraham** [comment]
Any ETA on this? Thanks!

**Comment by gekitz** [comment]
@pathonhauser any news on that?

**Comment by convey-mane** [comment]
Well ... 5 month now ...
My problem: I solely use this Resizeable Custom Crop (even stripped out everything else).
As we "scan" businesscards (take photos on e.g. iPhone5) to send 'em to a server for OCR, we on one hand want to crop all non-text (background, holding fingers and such) to reduce bandwidth/upload time - on the other hand, sent data has to be of high quality to get reasonable OCR-results.
And with an example-file of 399 KB uncropped resulting in 93 KB with Resizable Custom Crop - instead of 350 KB when test-cropping to the same frame with that simple Preview app on Mac (is it named "Preview"? In German it's "Vorschau"), there's not much left to OCR.
My suspicion is, it's the display-size, because on an iPad retina the difference between photo-resolution (well, indeed I use video-resolution at the moment, but that's another story) and display-resolution is minimal, resulting in good quality crops (a photo has e.g. 432 KB, with the crop still at 419 KB).

So, before I dive into GKImageCropView.m's croppedImage: is there already work done, will there be a solution anytime soon?

Greetings

**Comment by convey-mane** [comment]
found out something else, it apparently makes a huge difference in how the crop is done:
- if it's done by narrowing the cropping-rectangle (and maybe the image isn't scaled), or
- if the image is zoomed up, but the cropping-rectangle isn't touched (like with the other cropping methods);

the former results in the noticed poor quality, the latter not.
(with a test-image of 185 KB - it's made with my old (non-retina) iPad2 - the first crop is only at 63 KB, but the second is still at 126 KB, which seems to be a similar result as cropped with Preview app)!

So maybe it's not the display size ... but the scale of the cropping rectangle.

**Comment by phausero** [comment]
Hi there,

Sry that it took so long. I just took a look at it and i think I found a solution. I'm going to make a pull request on the weekend because I'm really busy right now and I want to test it in depth. Can you wait till then or do you want me to post the code right here and you have to test it on your own?

**Comment by convey-mane** [comment]
Well, as the colleague, which is doing the Server-side OCR-part also still has something to do - and is in holidays this and next week, I think it would be OK, when there's a tested solution on Monday, then I still can finish my part before he's back :-)
And with that also my boss will be satisfied 'till next week :-))
This week I have something else to finish anyway.

Very Fine.
Thanks a lot for the fast answer and (hopefully) the coming solution!

**Comment by convey-mane** [comment]
What could I say ... hats off, great, brilliant, ...!!!
:-)
Thanks a lot!

**Comment by phausero** [comment]
Great to hear that you like it! :-)

**Comment by gekitz** [comment]
I think we can close it now.
